name:                purelog
version:             0.1.0.0
github:              "pdnm/purelog"
license:             MIT
author:              "Phan Duc Nhat Minh"
copyright:           "2018 Phan Duc Nhat Minh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pdnm/purelog#readme>

dependencies:
- base >= 4.7 && < 5
- parsec == 3.*
- containers == 0.5.*

library:
  source-dirs: src

executables:
  purelog-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - purelog

tests:
  purelog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - purelog
